### ISSUE TITLE
Wrong closure in hook_frag.js

### ISSUE THREAD

**Issue by howmp** [nccgroup/house#16]
`{{ method_hook }}` is always last method in [here](https://github.com/nccgroup/house/blob/master/scripts/hook/hook_frag.js#L17)

**Comment by H4oK3** [comment]
Hey, I don't think that matters; it is in the loop and the temporary variable name should not matter. Let me know if you can find a case it is giving you the wrong outputs, otherwise I would just close the issue.
Also an issue with one line of word really confused me at the first place, I did not even know what are you talking about at the first place.

**Comment by howmp** [comment]
`{{ method_hook }}` variable will always the last of overloads

If print the `argumentTypes` in implementation function

```js
{{method_hook}}.argumentTypes.map(function(t){
    console.log(t.className)
}
```
With different overloads,the output always the last overload's  `argumentTypes`

**Comment by H4oK3** [comment]
Yes if u print them out; but it is a temp variable and **not** being used anywhere. If you want to print out the individual ones; you can add the print in the for loop. Am I making sense here? I am not sure what problem it is causing you, but House does not reuse the same overloaded function.

**Comment by howmp** [comment]
In House hook,the `argType` is javascript's type in `sendback`.

It should print java type for `sendback`,but can't use `{{method_hook}}`

**Comment by howmp** [comment]
[java.security.MessageDigest.update](https://docs.oracle.com/javase/8/docs/api/java/security/MessageDigest.html#update-byte-) with 4 overload, try to hook it.

Call with each overload in APK, and print `argumentTypes[index].className`.

You will see what's wrong.



```js
var a = [{
  cb:null,
  name:"name1"
},{
  cb:null,
  name:"name2"
}]

for(var i=0;i<a.length;i++){
  var method = a[i].name;
  a[i].cb = function(){
    console.log(method)
  }
}

a[0].cb()
a[1].cb()
// output :
// name2
// name2
```

**Comment by howmp** [comment]
The example with right way

```js
var a = [{
  cb: null,
  name: "name1"
}, {
  cb: null,
  name: "name2"
}]

for (var i = 0; i < a.length; i++) {
  var method = a[i].name;
  a[i].cb = function (name) {
    return function () {
      console.log(name)
    }
  }(method)
}

a[0].cb()
a[1].cb()
// output :
// name1
// name2
```

**Comment by H4oK3** [comment]
I know what are you talking about; the thing is House does not use `a[i]` outside the for loop; it is a **temporary variable** and is not carry on for further use; if what you need is to print it out; print it out in the loop where the temporary variable is assigned the correct value; 

But I can see a possible downside is; if you want to use `a[i]` as not only a temporary variable; I can update it a bit so it would be easier for you. Nevertheless; House is working fine at this point, `a[i]` value is not being carried on and all the return value/type are correct, because again, they are wrapped **in** the loop.
