### ISSUE TITLE
Classes won't load

### ISSUE THREAD

**Issue by dec0dOS** [nccgroup/house#5]
Keep getting message "[+] Updating intercept_conf with {"classname": "", "packagename": "com.ha0k3.overloads", "methodname": "", "overloadIndex": 0}" and nothing happens.
Recorded screencap:  https://streamable.com/w85wa

**Comment by H4oK3** [comment]
Hey @dec0dOS , I don't have that issue on my end and I am not quite sure why it didn't work on your end; but I would recommend you to do this and hopefully you will find the issue:

In your screenshot the console said "updating the json.." but the data value are empty string, I would assume something wrong happens at the websocket communication side; can you check your browser -> develop console and paste any error message here? Or can you try a different browser and disable other plugins? It might because there were some conflicts on the websocket stuff.

**Comment by H4oK3** [comment]
@dec0dOS lol it is a fun issue; I might get it updated in the future  :)
